config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#index'

  resources :notes

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates_presence_of :title
  validates_length_of :description, maximum: 1000
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all.order('created_at desc')
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      flash[:success] = "You successfully created a new note."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    @note.update_attributes(note_params)
    if @note.save
      flash[:success] = "You have successfully edited this note."
      redirect_to note_path(@note)
    else
      render :edit
    end
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to root_path
  end

  private

  def note_params
    params.require(:note).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container flash">
      <% flash.each do |message| %>
        <p><%= message[1] %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/notes/_errors.html.erb
<% if @note.errors %>
  <ul class="errors">
    <% @note.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/notes/_form.html.erb
<%= form_for @note, html: {class: 'form'} do |f| %>
  <%= f.label 'title' %>
  <%= f.text_field :title %>

  <%= f.label 'description' %>
  <%= f.text_area :description %>

  <%= f.submit 'Save Note', class:"wide-button save-button" %>
<% end %>

app/views/notes/edit.html.erb
<div class="container">
  <% if @note.errors %>
    <ul class="errors">
      <% @note.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <h1>edit note</h1>
  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<div class="container">
  <%= link_to 'create a new note', new_note_path, class:"edit-button medium-button" %>
  <h1>my notes</h1>

  <table>
    <thead>
      <th>Title</th>
      <th>Description</th>
      <th> </th>
      <th> </th>
    </thead>
  <% @notes.each do |note| %>
    <tr>
      <td><%= link_to note.title, note_path(note) %></td>
      <td><%= note.description %></td>
      <td><%= link_to 'Edit', edit_note_path(note), class:"edit-button small-button" %></td>
      <td><%= link_to 'Delete', note_path(note), :method => 'delete', class:"delete-button small-button" %></td>
    </tr>
  <% end %>
</table>

</div>

app/views/notes/new.html.erb
<div class="container">

  <%= render 'errors' %>

  <h1>create a new note</h1>
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div class="container">
  <h1>Note</h1>
  <h3><%= @note.title %></h3>
  <div class="description">
    <p><%= @note.description %></p>
  </div>
  <p>created at: <%= @note.created_at.strftime('%m/%d/%Y') %></p>
  <p>updated at: <%= @note.updated_at.strftime('%m/%d/%Y') %></p>
  <%= link_to 'Edit', edit_note_path(@note), class:"edit-button wide-button" %>
  <%= link_to 'Delete', note_path(@note), :method => 'delete', class:"delete-button wide-button" %>
  <%= link_to 'Home', root_path, class:"home-button wide-button" %>
</div>